services:
  # FastAPI Backend Service
  - type: web
    name: pod-failure-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    
  # Streamlit Frontend Service  
  - type: web
    name: pod-failure-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0